# Generated by Django 5.0.2 on 2024-02-12 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pag_inicio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='posteos',
            new_name='posteo',
        ),
    ]
