# Generated by Django 5.0.2 on 2024-02-12 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pag_inicio', '0002_rename_posteos_posteo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posteo',
            name='slug',
        ),
    ]
