# Generated by Django 5.0.2 on 2024-02-12 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pag_inicio', '0003_remove_posteo_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posteo',
            name='fecha_publicacion',
        ),
    ]
