# Generated by Django 5.0.2 on 2024-02-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pag_inicio', '0004_remove_posteo_fecha_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteo',
            name='fecha_post',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='posteo',
            name='texto',
            field=models.TextField(max_length=500),
        ),
    ]
